/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagement;

import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.Date;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author DELL
 */
public class add_event extends javax.swing.JFrame {
    /**
     * Creates new form add_event
     */
    public add_event() {
        initComponents();
//        jPanel2.setBackground(new Color(0,0,0,180));
        jPanel3.setBackground(new Color(0,0,0,80));
    }
    
    String logname;
    public add_event(String name){
        initComponents();
//        currentdate();
        this.logname = name;
        getusername.setText(String.valueOf(logname));
//        jPanel2.setBackground(new Color(0,0,0,60));
        jPanel3.setBackground(new Color(0,0,0,60));
//        rate();
//        total();
    }
    
     public static Connection myConnection(){
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl="jdbc:mysql://localhost:3306/login?"+"user=root&password=root";
            con = DriverManager.getConnection(connectionUrl);
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(add_event.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(add_event.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    }
     
    public static int okcancel(String theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public static int okcancel(int theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public static int okcancel(Date theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        getusername = new javax.swing.JLabel();
        add_event = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        audience1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        food_details1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        stage_details = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        decoration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        show_date = new javax.swing.JLabel();
        show_phone = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        getusername.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        getusername.setForeground(new java.awt.Color(255, 255, 255));
        getusername.setText("username");

        add_event.setBackground(new java.awt.Color(153, 153, 153));
        add_event.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_event.setForeground(new java.awt.Color(255, 255, 255));
        add_event.setText("ADD EVENT");
        add_event.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add_event.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_eventMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("EVENT MANAGEMENT SYSTEM");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/icons8-user-16.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(getusername, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(384, 384, 384)
                .addComponent(add_event)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getusername)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_event))
                        .addGap(14, 14, 14))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1420, 80));

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel1.add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 473, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arno Pro Caption", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BOOKING");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Back");
        back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 40, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 473, 52));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        date1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                date1MouseExited(evt);
            }
        });
        date1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                date1KeyReleased(evt);
            }
        });
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 473, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATE OF EVENT :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 473, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NUMBER:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AUDIENCE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, -1, -1));

        audience1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        audience1.setMaximumRowCount(3);
        audience1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300" }));
        audience1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audience1MouseClicked(evt);
            }
        });
        audience1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audience1ActionPerformed(evt);
            }
        });
        jPanel1.add(audience1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 470, 40));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FOOD TYPE :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 550, -1, -1));

        food_details1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        food_details1.setMaximumRowCount(3);
        food_details1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VEG", "NON -VEG", "BOTH" }));
        food_details1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                food_details1MouseClicked(evt);
            }
        });
        food_details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_details1ActionPerformed(evt);
            }
        });
        jPanel1.add(food_details1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 470, 40));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STAGE TYPE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 610, -1, -1));

        stage_details.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stage_details.setMaximumRowCount(3);
        stage_details.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPEN AIR", "BALLOONS", "FLOWERS" }));
        stage_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stage_detailsMouseClicked(evt);
            }
        });
        stage_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stage_detailsActionPerformed(evt);
            }
        });
        jPanel1.add(stage_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 600, 470, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 123, 1420, 10));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reset.setBackground(new java.awt.Color(204, 204, 204));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel3.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 620, 82, -1));

        submit.setBackground(new java.awt.Color(204, 204, 204));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel3.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 620, -1, -1));

        decoration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decorationActionPerformed(evt);
            }
        });
        jPanel3.add(decoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 473, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("EXTRA TYPE:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 760, 690));

        show_date.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        show_date.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(show_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 360, 100, 20));

        show_phone.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        show_phone.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(show_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 420, 117, 19));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/pexels-polina-kovaleva-5430720.jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1920, 870));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EXTRA TYPE:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("EXTRA TYPE:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 670, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 856));

        setSize(new java.awt.Dimension(1435, 893));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        dispose();
        login l=new login();
        l.show();
        //        getusername=login.getText(.name);

    }//GEN-LAST:event_jLabel2MouseClicked

    private void add_eventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_eventMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_add_eventMouseClicked

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        // TODO add your handling code here
        dispose();
        String bname=logname;
        new home(bname).setVisible(true);
    }//GEN-LAST:event_back_btnMouseClicked

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved

    }//GEN-LAST:event_jLabel10MouseMoved

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        // TODO add your handling code here:
        dispose();
        new add_event(logname).setVisible(true);

    }//GEN-LAST:event_resetActionPerformed

//    private static boolean isvalid(String s){
//        Pattern p=Pattern.compile("^[0-9][0,12]$");
//        Matcher m =p.matcher(phone1.getText());
//        return (m.matches());
//    }
    
    public String decoration1="";
    public String orgname,name,audience,phone1,address1,food_value,stage_value,datee="",org_det;
    public String f_rate,s_rate,a_rate;
    public int ar,fr,sr,total;
    public Date date_vali,date_vali2; 
    public String cdate;
    public Date date2,date3;
    public int uid;
    public Date adate_vali,adate3;
    public String adate;
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        Connection con = myConnection();
        try{
            PreparedStatement prest,prest1,prest2,prest3,prest4,prest5;
            
            SimpleDateFormat sss = new SimpleDateFormat("yyyy-MM-dd");
            date2=new Date();
            cdate=sss.format(date2);
            date_vali2=sss.parse(cdate);
            if(((JTextField)date1.getDateEditor().getUiComponent()).getText().isEmpty()){
                show_date.setText("Invalid");
            }
            else{
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                datee=sdf.format(date1.getDate());
                date3=sdf.parse(datee);
                date_vali=sdf.parse(datee);
                
                if(date2.compareTo(date_vali)>=date3.compareTo(date_vali2)){
                    show_date.setText("Invalid");
                }
                else{
                    show_date.setText("");
                }
            }
            orgname=logname;
            name=uname.getText();
            audience = audience1.getSelectedItem().toString();
            phone1=phone.getText();
            address1=address.getText();
            decoration1=decoration.getText();
            food_value = food_details1.getSelectedItem().toString();
            stage_value = stage_details.getSelectedItem().toString();
           
            //audience
            String a1=audience;
            String sq3="SELECT * FROM audience_details where audience_name='"+a1+"'";
            prest2= con.prepareStatement(sq3);
            ResultSet rs2 = prest2.executeQuery(sq3);
            while(rs2.next()){
                a_rate = String.valueOf(rs2.getInt("audience_rate"));
                ar=Integer.parseInt(a_rate);
            }
            //food
            String f1=food_value;
            String sq2="SELECT * FROM food_details where food_name='"+f1+"'";
            prest1= con.prepareStatement(sq2);
            ResultSet rs1 = prest1.executeQuery(sq2);
            while(rs1.next()){
                f_rate = String.valueOf(rs1.getInt("food_rate"));
                fr=Integer.parseInt(f_rate);
            }
            //stage
            String s1=stage_value;
            String sq4="SELECT * FROM stage_details where stage_name='"+s1+"'";
            prest3= con.prepareStatement(sq4);
            ResultSet rs3 = prest3.executeQuery(sq4);
            while(rs3.next()){
                s_rate = String.valueOf(rs3.getInt("stage_rate"));
                sr=Integer.parseInt(s_rate);
            }
            
            //event name
            
            String sq5="SELECT event_details,uid FROM user_login where username='"+logname+"'";
            prest4= con.prepareStatement(sq5);
            ResultSet rs4 = prest4.executeQuery(sq5);
            while(rs4.next()){
                org_det = rs4.getString("event_details");
                uid = rs4.getInt("uid");
            }
            
//            String sq6="SELECT username FROM user_login where uid='"+uid+"'";
//            prest5=con.prepareStatement(sq6);
//            ResultSet rs5=prest5.executeQuery(sq6);
//            while(rs5.next()){
//                String uname=rs5.getString("username");
//            }

            //total
            total=ar+fr+sr;
           
            //validation
           
            int length=phone1.length();
            String PATTERN ="^\\d{10}$";
            Pattern p=Pattern.compile(PATTERN);
            Matcher m =p.matcher(phone.getText());
            
            if(m.matches()){
                show_phone.setText("");
            }
            else{
                show_phone.setText("Invalid");
            }
            
            if(name.equals("") || address1.equals("")||phone1.equals("")||length!=10||!m.matches()||((JTextField)date1.getDateEditor().getUiComponent()).getText().isEmpty()||date2.compareTo(date_vali)>=date3.compareTo(date_vali2)){
                okcancel("All field need to be filled!");
            }
            else{
                String sql ="INSERT INTO event_details(user_name,event_date,food,stage,org_details,phone,address,audience,decoration,total,uid)VALUES('"+name+"','"+datee+"','"+food_value+"','"+stage_value+"','"+org_det+"','"+phone1+"','"+address1+"','"+audience+"','"+decoration1+"','"+total+"','"+uid+"');";
                prest= con.prepareStatement(sql);
                int count = prest.executeUpdate();
                if(count>0){
                    int i = okcancel("NEW EVENT ADDED");
                    System.out.println("ret:"+i);
                    dispose();
                    new add_event(logname).setVisible(true);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(add_event.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void stage_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stage_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stage_detailsActionPerformed

    private void stage_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stage_detailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stage_detailsMouseClicked

    private void food_details1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_details1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food_details1ActionPerformed

    private void food_details1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food_details1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_food_details1MouseClicked

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void audience1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audience1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_audience1MouseClicked

    private void audience1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audience1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audience1ActionPerformed

    private void decorationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decorationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decorationActionPerformed

   
    private void date1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_date1KeyReleased

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phoneKeyPressed

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_phoneMouseClicked

    public String trydatee;
    public Date trydate3,date_vali3;
    private void date1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_date1MouseExited
      
    }//GEN-LAST:event_date1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_event.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_event().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_event;
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> audience1;
    private javax.swing.JLabel back_btn;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField decoration;
    private javax.swing.JComboBox<String> food_details1;
    private javax.swing.JLabel getusername;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField phone;
    private javax.swing.JButton reset;
    private javax.swing.JLabel show_date;
    private javax.swing.JLabel show_phone;
    private javax.swing.JComboBox<String> stage_details;
    private javax.swing.JButton submit;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
