/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagement;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class homeNext extends javax.swing.JFrame {

    /**
     * Creates new form homeNext
     */
    public homeNext() {
        initComponents();
        getuserlogin();
        setPersonTableData2(logname);
    }
    
    public String logname;
    private int id;
    
    public homeNext(String name){
        initComponents();
        this.logname=name;
        getusername.setText(String.valueOf(logname));
        getuserlogin();
        setPersonTableData2(logname);
    }
    
    public static int okcancel(String theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public static int okcancel(int theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public static Connection myConnection(){
        Connection con = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl="jdbc:mysql://localhost:3306/login?"+"user=root&password=root";
            con = DriverManager.getConnection(connectionUrl);
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        show_phone = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        getusername = new javax.swing.JLabel();
        add_event = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        receipt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        back_btn1 = new javax.swing.JLabel();
        getname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        geteventid1 = new javax.swing.JLabel();
        geteventid = new javax.swing.JLabel();
        audience1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        food_details1 = new javax.swing.JComboBox<>();
        stage_details = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        decoration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        show_date = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        geteventid2 = new javax.swing.JLabel();
        geteventid3 = new javax.swing.JLabel();
        geteventid4 = new javax.swing.JLabel();
        geteventid5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Logout");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 10, -1, -1));

        show_phone.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        show_phone.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(show_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 400, 100, 20));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        getusername.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        getusername.setForeground(new java.awt.Color(255, 255, 255));
        getusername.setText("username");

        add_event.setBackground(new java.awt.Color(153, 153, 153));
        add_event.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add_event.setForeground(new java.awt.Color(255, 255, 255));
        add_event.setText("ADD EVENT");
        add_event.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        add_event.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_eventMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("EVENT MANAGEMENT SYSTEM");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        jLabel10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel10MouseMoved(evt);
            }
        });

        receipt.setBackground(new java.awt.Color(0, 0, 204));
        receipt.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        receipt.setForeground(new java.awt.Color(255, 255, 255));
        receipt.setText("    RECIPTE");
        receipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        receipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/icons8-user-16.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(getusername, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(259, 259, 259)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(add_event)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getusername)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_event)
                            .addComponent(receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1490, 80));

        test.setBackground(new java.awt.Color(0, 0, 0));
        test.setFont(new java.awt.Font("OCR A Extended", 1, 36)); // NOI18N
        test.setForeground(new java.awt.Color(255, 255, 255));
        test.setText("BOOKING DETAILS");
        test.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testMouseClicked(evt);
            }
        });
        jPanel1.add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        back_btn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_btn1.setForeground(new java.awt.Color(255, 255, 255));
        back_btn1.setText("Back");
        back_btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        back_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btn1MouseClicked(evt);
            }
        });
        jPanel1.add(back_btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        getname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getnameActionPerformed(evt);
            }
        });
        jPanel1.add(getname, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 200, 270, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAME:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, -1, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 250, 270, 50));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATE OF EVENT :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, -1, -1));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 320, 270, 30));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 370, 270, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NUMBER:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 380, -1, -1));

        geteventid1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid1.setForeground(new java.awt.Color(255, 255, 255));
        geteventid1.setText("Event ID :");
        jPanel1.add(geteventid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 130, -1, -1));

        geteventid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid.setForeground(new java.awt.Color(255, 255, 255));
        geteventid.setText("...");
        jPanel1.add(geteventid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 130, 40, -1));

        audience1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        audience1.setMaximumRowCount(3);
        audience1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300" }));
        audience1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                audience1MouseClicked(evt);
            }
        });
        audience1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audience1ActionPerformed(evt);
            }
        });
        jPanel1.add(audience1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 430, 270, 30));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AUDIENCE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 440, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FOOD TYPE :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 500, -1, 20));

        food_details1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        food_details1.setMaximumRowCount(3);
        food_details1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VEG", "NON -VEG", "BOTH" }));
        food_details1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                food_details1MouseClicked(evt);
            }
        });
        food_details1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                food_details1ActionPerformed(evt);
            }
        });
        jPanel1.add(food_details1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 490, 270, 30));

        stage_details.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stage_details.setMaximumRowCount(3);
        stage_details.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OPEN AIR", "BALLOONS", "FLOWERS", "" }));
        stage_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stage_detailsMouseClicked(evt);
            }
        });
        stage_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stage_detailsActionPerformed(evt);
            }
        });
        jPanel1.add(stage_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 560, 270, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STAGE TYPE :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 570, -1, -1));

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setText("DELETE");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 720, -1, -1));

        update.setBackground(new java.awt.Color(204, 204, 204));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 720, -1, -1));

        decoration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decorationActionPerformed(evt);
            }
        });
        jPanel1.add(decoration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 620, 270, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Click on the table to edit or delete");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 250, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EVENT ID", "USER NAME", "EVENT DATE", "FOOD", "STAGE", "PHONE", "ADDRESS", "AUDIENCE", "EXTRA ITEMS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 1030, 310));

        show_date.setFont(new java.awt.Font("Segoe UI", 3, 10)); // NOI18N
        show_date.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(show_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 350, 100, 20));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DECORATION TYPE:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/pexels-polina-kovaleva-5430720.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1500, 760));

        geteventid2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid2.setForeground(new java.awt.Color(255, 255, 255));
        geteventid2.setText("Event ID :");
        jPanel1.add(geteventid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, -1, -1));

        geteventid3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid3.setForeground(new java.awt.Color(255, 255, 255));
        geteventid3.setText("Event ID :");
        jPanel1.add(geteventid3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, -1, -1));

        geteventid4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid4.setForeground(new java.awt.Color(255, 255, 255));
        geteventid4.setText("Event ID :");
        jPanel1.add(geteventid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, -1, -1));

        geteventid5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        geteventid5.setForeground(new java.awt.Color(255, 255, 255));
        geteventid5.setText("Event ID :");
        jPanel1.add(geteventid5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1504, 797));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:

        dispose();
        login l=new login();
        l.show();
        //        getusername=login.getText(.name);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void add_eventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_eventMouseClicked
        // TODO add your handling code here:
        dispose();
        String loginname=logname;
        new add_event(loginname).setVisible(true);
    }//GEN-LAST:event_add_eventMouseClicked

    private void jLabel10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseMoved

    }//GEN-LAST:event_jLabel10MouseMoved

    private void getnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getnameActionPerformed

    private void food_details1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_food_details1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_food_details1MouseClicked

    private void food_details1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_food_details1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_food_details1ActionPerformed

    private void stage_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stage_detailsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stage_detailsMouseClicked

    private void stage_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stage_detailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stage_detailsActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection();
        if(id!=0){
            try{
                PreparedStatement prest;
                String sql ="delete from event_details where eid="+id;
                prest= con.prepareStatement(sql);
                prest.execute(sql);
                int i = okcancel("Deleted!...");
                System.out.println(" "+i);
                new homeNext(logname).setVisible(true);
                dispose();
                con.close();
            } catch (SQLException ex) {
                 Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    public Date date_vali,date_vali2; 
    public String cdate;
    public Date date2,date3;
    public String f_rate,s_rate,a_rate,date;
    public int ar,fr,sr,total;
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection con = myConnection();
        if(id!=0){
        try{
            String getname1=getname.getText();
                
            if(((JTextField)date1.getDateEditor().getUiComponent()).getText().isEmpty()){
                show_date.setText("Invalid");
            }
            else{
                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                date=sdf1.format(date1.getDate());
                date3=sdf1.parse(date);
                date_vali=sdf1.parse(date);
                
                SimpleDateFormat sss = new SimpleDateFormat("yyyy-MM-dd");
                date2=new Date();
                cdate=sss.format(date2);
                date_vali2=sss.parse(cdate);
            
                
                if(date2.compareTo(date_vali)>=date3.compareTo(date_vali2)){
                    show_date.setText("Invalid");
                }
                else{
                    show_date.setText("");
                }
            }
            String food_value = food_details1.getSelectedItem().toString();
            String stage_value = stage_details.getSelectedItem().toString();
            String phone1=phone.getText();
            String address1=address.getText();
            String audience = audience1.getSelectedItem().toString();
            String decoration1=decoration.getText();
                
            PreparedStatement prest,prest1,prest2,prest3;
            
            
            String a1=audience;
            String sq3="SELECT * FROM audience_details where audience_name='"+a1+"'";
            prest2= con.prepareStatement(sq3);
            ResultSet rs2 = prest2.executeQuery(sq3);
            while(rs2.next()){
                a_rate = String.valueOf(rs2.getInt("audience_rate"));
                ar=Integer.parseInt(a_rate);
            }
            //food
            String f1=food_value;
            String sq2="SELECT * FROM food_details where food_name='"+f1+"'";
            prest1= con.prepareStatement(sq2);
            ResultSet rs1 = prest1.executeQuery(sq2);
            while(rs1.next()){
                f_rate = String.valueOf(rs1.getInt("food_rate"));
                fr=Integer.parseInt(f_rate);
            }
            //stage
            String s1=stage_value;
            String sq4="SELECT * FROM stage_details where stage_name='"+s1+"'";
            prest3= con.prepareStatement(sq4);
            ResultSet rs3 = prest3.executeQuery(sq4);
            while(rs3.next()){
                s_rate = String.valueOf(rs3.getInt("stage_rate"));
                sr=Integer.parseInt(s_rate);
            }
            total=ar+fr+sr;
            
            String PATTERN ="^\\d{10}$";
            Pattern p=Pattern.compile(PATTERN);
            Matcher m =p.matcher(phone.getText());
            
            if(m.matches()){
                show_phone.setText("");
            }
            else{
                show_phone.setText("Invalid");
            }
            
            if(getname1.equals("")||address1.equals("")||phone1.equals("")||phone1.length()!=10||!m.matches()||((JTextField)date1.getDateEditor().getUiComponent()).getText().isEmpty()||date2.compareTo(date_vali)>=date3.compareTo(date_vali2)){
                okcancel("All field need to be filled!");
            }
            else{
            String sql ="update event_details set user_name='"+getname1+"',event_date='"+date+"',food='"+food_value+"',stage='"+stage_value+"',phone='"+phone1+"',address='"+address1+"',audience='"+audience+"',decoration='"+decoration1+"',total='"+total+"' where eid='"+id+"'";
            prest= con.prepareStatement(sql);
            prest.execute(sql);
            int i = okcancel("Updating...");
            System.out.println(" "+i);
            new homeNext(logname).setVisible(true);
            dispose();
            con.close();
            id =0;
            }
        }catch (SQLException ex) {
            Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (ParseException ex) {
                Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    public int uid;
    private void getuserlogin(){
        Connection con = myConnection();
        try{
            String bname = logname;
            PreparedStatement prest;
            String sql1 ="SELECT uid FROM user_login WHERE username='"+bname+"'";
            prest= con.prepareStatement(sql1);
            ResultSet rs = prest.executeQuery(sql1);
            while(rs.next()){
                uid=rs.getInt("uid");
            }
        }catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    private void setPersonTableData2(String lname){
          Connection con = myConnection();
        try{ 
            String bname = lname;
            PreparedStatement prest;
            String sql1 ="SELECT * FROM event_details where uid='"+uid+"' ORDER BY event_date DESC";
            prest= con.prepareStatement(sql1);
            ResultSet rs = prest.executeQuery(sql1);
            while(rs.next()){
                String id  = String.valueOf(rs.getInt("eid"));
                String un = rs.getString("user_name");
                String ed = rs.getString("event_date");
                String fd = rs.getString("food");
                String sg = rs.getString("stage");
                String pn = rs.getString("phone");
                String ad = rs.getString("address");
                String au = rs.getString("audience");
                String dc = rs.getString("decoration");
                String tbData[]={id,un,ed,fd,sg,pn,ad,au,dc};
                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
            }catch (SQLException ex) {
            Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    
    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void audience1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_audience1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_audience1MouseClicked

    private void audience1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audience1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audience1ActionPerformed

    private void back_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btn1MouseClicked
        // TODO add your handling code here
        dispose();
        String bname=logname;
        new home(bname).setVisible(true);
    }//GEN-LAST:event_back_btn1MouseClicked

    private void decorationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decorationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decorationActionPerformed

    private void testMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_testMouseClicked

    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        Connection con = myConnection(); 
        id=Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        String fd=jTable1.getValueAt(jTable1.getSelectedRow(),3).toString();
        String st=jTable1.getValueAt(jTable1.getSelectedRow(),4).toString();
        String ad=jTable1.getValueAt(jTable1.getSelectedRow(),7).toString();
        int am=id;
        geteventid.setText(String.valueOf(am));
        try{
            PreparedStatement prest;
            String sql ="select * from event_details where eid="+id;
            prest = con.prepareStatement(sql);
            ResultSet rs = prest.executeQuery();
            while(rs.next()){
                getname.setText(rs.getString(2));
                date1.setDate(rs.getDate(3));
                phone.setText(rs.getString(8));                
                address.setText(rs.getString(9));
                decoration.setText(rs.getString(11));
                switch(fd){
                    case "VEG":
                        food_details1.setSelectedIndex(0);
                        break;
                    case "NON -VEG":
                        food_details1.setSelectedIndex(1);
                        break;
                    case "BOTH":
                        food_details1.setSelectedIndex(2);
                        break;
                    default:
                        food_details1.setSelectedIndex(2);
                }
                switch(st){
                    case "OPEN AIR":
                        stage_details.setSelectedIndex(0);
                        break;
                    case "BALLOONS":
                        stage_details.setSelectedIndex(1);
                        break;
                    case "FLOWERS":
                        stage_details.setSelectedIndex(2);
                        break;
                    default:
                        stage_details.setSelectedIndex(2);
                }
                switch(ad){
                    case "100":
                        audience1.setSelectedIndex(0);
                        break;
                    case "200":
                        audience1.setSelectedIndex(1);
                        break;
                    case "300":
                        audience1.setSelectedIndex(2);
                        break;
                    default:
                        audience1.setSelectedIndex(2);  
                }
            }
            rs.close();
            prest.close();
        }catch (SQLException ex) {
            Logger.getLogger(homeNext.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
        // TODO add your handling code here:
        dispose();
        new receipt(id,logname).setVisible(true);
    }//GEN-LAST:event_receiptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeNext.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeNext().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_event;
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> audience1;
    private javax.swing.JLabel back_btn1;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextField decoration;
    private javax.swing.JButton delete;
    private javax.swing.JComboBox<String> food_details1;
    private javax.swing.JLabel geteventid;
    private javax.swing.JLabel geteventid1;
    private javax.swing.JLabel geteventid2;
    private javax.swing.JLabel geteventid3;
    private javax.swing.JLabel geteventid4;
    private javax.swing.JLabel geteventid5;
    private javax.swing.JTextField getname;
    private javax.swing.JLabel getusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel receipt;
    private javax.swing.JLabel show_date;
    private javax.swing.JLabel show_phone;
    private javax.swing.JComboBox<String> stage_details;
    private javax.swing.JLabel test;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
