/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EventManagement;

import static EventManagement.event_details.myConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author DELL
 */
public class sales_details extends javax.swing.JFrame {

    /**
     * Creates new form sales_details
     */
    
    public sales_details() {
        initComponents();
        setPersonTableData();
        mbtotal();
        showBarChart();
        total();
        jPanel2.setBackground(new Color(0,0,0,80));
        jPanel3.setBackground(new Color(0,0,0,80));
        this.setSize(1435, 760);
//        showPieChart();
    }

    public static int okcancel(Date theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public static int okcancel(int theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public String mtmar="",btbar="";
    public int tmtmar,tbtbar;
    private void mbtotal(){
        Connection con = myConnection();
        try{
            PreparedStatement prest,prest1;
            String sql ="SELECT sum(total) FROM event_details WHERE org_details='MARRIAGE'";
            String sql1 ="SELECT sum(total) FROM event_details WHERE org_details='BIRTHDAY'";
            prest= con.prepareStatement(sql);
            prest1= con.prepareStatement(sql1);
            ResultSet rs = prest.executeQuery(sql);
            ResultSet rs1 = prest1.executeQuery(sql1);
            while(rs.next()){
                mtmar = rs.getString("sum(total)");
                tmtmar=Integer.parseInt(mtmar);
            }
            while(rs1.next()){
                btbar = rs1.getString("sum(total)");
                tbtbar=Integer.parseInt(btbar);
            }
            }catch (SQLException ex) {
            Logger.getLogger(sales_details.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
  
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        event_details = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();
        org_details = new javax.swing.JLabel();
        sales_details = new javax.swing.JLabel();
        addorg = new javax.swing.JLabel();
        dltorg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        gettotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        end_date = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        show_date2 = new javax.swing.JLabel();
        start_date = new com.toedter.calendar.JDateChooser();
        date_sort = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        show_date1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        event_details.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        event_details.setForeground(new java.awt.Color(255, 255, 255));
        event_details.setText("BOOKING DETAILS");
        event_details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        event_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        event_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                event_detailsMouseClicked(evt);
            }
        });
        jPanel2.add(event_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 191, 156, -1));

        logout_btn.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("LOGOUT");
        logout_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), null, new java.awt.Color(255, 255, 255)));
        logout_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });
        jPanel2.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        org_details.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        org_details.setForeground(new java.awt.Color(255, 255, 255));
        org_details.setText("ORGANISER DETAILS");
        org_details.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        org_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        org_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                org_detailsMouseClicked(evt);
            }
        });
        jPanel2.add(org_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 253, -1, -1));

        sales_details.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        sales_details.setForeground(new java.awt.Color(255, 255, 255));
        sales_details.setText("SALES DETAILS");
        sales_details.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sales_details.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_detailsMouseClicked(evt);
            }
        });
        jPanel2.add(sales_details, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 319, 156, -1));

        addorg.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        addorg.setForeground(new java.awt.Color(255, 255, 255));
        addorg.setText("ADD ORGANISER");
        addorg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        addorg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addorg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addorgMouseClicked(evt);
            }
        });
        jPanel2.add(addorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 378, 156, -1));

        dltorg.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        dltorg.setForeground(new java.awt.Color(255, 255, 255));
        dltorg.setText("DELETE ORGANISER");
        dltorg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        dltorg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dltorg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dltorgMouseClicked(evt);
            }
        });
        jPanel2.add(dltorg, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 437, 156, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/icons8-admin-64.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EVENT MANAGEMENT SYSTEM");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setLayout(new java.awt.BorderLayout());
        jPanel3.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 500, 280));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EVENT ID", "USER NAME", "EVENT DATE", "ORG ID", "TOTEL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1120, 220));

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("End Date");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 30, -1, 20));

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL ");

        gettotal.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        gettotal.setText("TOTAL :");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/icons8-total-sales-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addGap(33, 33, 33)
                        .addComponent(gettotal))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel4))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(gettotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 140));

        end_date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                end_dateKeyReleased(evt);
            }
        });
        jPanel3.add(end_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 140, -1));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("SALES DETAILS");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 25));

        show_date2.setFont(new java.awt.Font("Agency FB", 3, 12)); // NOI18N
        show_date2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(show_date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 40, 20));
        jPanel3.add(start_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 140, -1));

        date_sort.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        date_sort.setText("SORT");
        date_sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_sortActionPerformed(evt);
            }
        });
        jPanel3.add(date_sort, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Start Date");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, -1, 20));

        show_date1.setFont(new java.awt.Font("Agency FB", 3, 12)); // NOI18N
        show_date1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(show_date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 40, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 1150, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EventManagement/pexels-polina-kovaleva-5430720.jpg"))); // NOI18N
        jLabel1.setText("frtcyfghhg");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 1450, 730));

        setSize(new java.awt.Dimension(1424, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private void showBarChart(){
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(tmtmar, "Amount", "MARRIAGE");
        dataset.setValue(tbtbar, "Amount", "BIRTHDAY");
        
        JFreeChart chart = ChartFactory.createBarChart("MOST SALES","EVENT","TOTAL AMOUNT",
                dataset, PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot categoryPlot = chart.getCategoryPlot();
        //categoryPlot.setRangeGridlinePaint(Color.BLUE);
        categoryPlot.setBackgroundPaint(Color.WHITE);
        BarRenderer renderer = (BarRenderer) categoryPlot.getRenderer();
        Color clr3 = new Color(204,0,51);
        renderer.setSeriesPaint(0, clr3);
        
        ChartPanel barpChartPanel = new ChartPanel(chart);
        panelBarChart.removeAll();
        panelBarChart.add(barpChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    } 
    
     
    private void setPersonTableData(){
        Connection con = myConnection();
        try{
            PreparedStatement prest;
            String sql ="SELECT * FROM event_details  ORDER BY event_date DESC";
            prest= con.prepareStatement(sql);
            ResultSet rs = prest.executeQuery(sql);
            while(rs.next()){
                String id  = String.valueOf(rs.getInt("eid"));
                String un = rs.getString("user_name");
                String ed = rs.getString("event_date");
                String on = rs.getString("uid");
                String tl = rs.getString("total");
                String tbData[]={id,un,ed,on,tl};
                DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
                tblModel.addRow(tbData);
            }
            
            }catch (SQLException ex) {
            Logger.getLogger(sales_details.class.getName()).log(Level.SEVERE, null, ex);
            }
    } 
    
    public String dc;
    public int t;
    private void total(){
        Connection con = myConnection();
        try{
            PreparedStatement prest;
            String sql ="SELECT sum(total) FROM event_details";
            prest= con.prepareStatement(sql);
            ResultSet rs2 = prest.executeQuery(sql);
            while(rs2.next()){
                dc = rs2.getString("sum(total)");
                t=Integer.parseInt(dc);
            }
            gettotal.setText(String.valueOf(t));
            }catch (SQLException ex) {
            Logger.getLogger(sales_details.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
//    private void showPieChart(){
//        //create dataset
//        DefaultPieDataset barDataset = new DefaultPieDataset( );
//        barDataset.setValue( "MARRIAGE" , new Double( 80 ) );  
//        barDataset.setValue( "BIRTHDAY" , new Double( 20 ) );
//        JFreeChart piechart = ChartFactory.createPieChart("Most Selected Event",barDataset, false,true,false);//explain
//        PiePlot piePlot =(PiePlot) piechart.getPlot();
//        piePlot.setSectionPaint("MARRIAGE", new Color(255,255,102));
//        piePlot.setSectionPaint("BIRTHDAY", new Color(102,255,102));
//        piePlot.setBackgroundPaint(Color.white);
//        ChartPanel barChartPanel = new ChartPanel(piechart);
//        panelBarChart.removeAll();
//        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
//        panelBarChart.validate();
//    }

    
    private void event_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_event_detailsMouseClicked
        // TODO add your handling code here:
        dispose();
        event_details e = new event_details();
        e.show();
    }//GEN-LAST:event_event_detailsMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        dispose();
        login l=new login();
        l.show();
    }//GEN-LAST:event_logout_btnMouseClicked

    private void org_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_org_detailsMouseClicked
        // TODO add your handling code here:
        dispose();
        admin a= new admin();
        a.show();
    }//GEN-LAST:event_org_detailsMouseClicked

    private void sales_detailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_detailsMouseClicked
        // TODO add your handling code here:
        dispose();
        new sales_details().setVisible(true);
    }//GEN-LAST:event_sales_detailsMouseClicked

    private void addorgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addorgMouseClicked
        // TODO add your handling code here:
        dispose();
        signup s = new signup();
        s.show();
    }//GEN-LAST:event_addorgMouseClicked

    private void dltorgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dltorgMouseClicked
        // TODO add your handling code here:
        dispose();
        org_dlt d = new org_dlt();
        d.show();
    }//GEN-LAST:event_dltorgMouseClicked
    
    private void end_dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_end_dateKeyReleased
        // TODO add your handling code here:
  
    }//GEN-LAST:event_end_dateKeyReleased

    public static int okcancel(String theMessage){
        int result=JOptionPane.showConfirmDialog((Component)null,theMessage,"alert",JOptionPane.OK_CANCEL_OPTION);
        return result;
    }
    
    public String sdate="",edate="";
    private void date_sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_sortActionPerformed
            // TODO add your handling code here:
            if(((JTextField)start_date.getDateEditor().getUiComponent()).getText().isEmpty()||((JTextField)end_date.getDateEditor().getUiComponent()).getText().isEmpty()){
                okcancel("Date is Invalid");
            }
            else{
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                sdate=sdf.format(start_date.getDate());
                edate=sdf.format(end_date.getDate());
                okcancel("SORTING");
                new sales_details_sort(sdate,edate).setVisible(true);  
                dispose();
            }
            
    }//GEN-LAST:event_date_sortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sales_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sales_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sales_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sales_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {   
                new sales_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addorg;
    private javax.swing.JButton date_sort;
    private javax.swing.JLabel dltorg;
    private com.toedter.calendar.JDateChooser end_date;
    private javax.swing.JLabel event_details;
    private javax.swing.JLabel gettotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel org_details;
    private javax.swing.JPanel panelBarChart;
    private javax.swing.JLabel sales_details;
    private javax.swing.JLabel show_date1;
    private javax.swing.JLabel show_date2;
    private com.toedter.calendar.JDateChooser start_date;
    // End of variables declaration//GEN-END:variables
}
